version: '3'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: kaggle
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  spark:
    build: .
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - .:/home/jovyan/work
    depends_on:
      - db
